# Generated by Django 5.0.6 on 2024-05-29 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='profile_image',
            field=models.ImageField(upload_to='profile_image'),
        ),
    ]
