# Generated by Django 5.0.6 on 2024-05-29 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageApp', '0002_alter_usermodel_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='profile_image',
            field=models.ImageField(upload_to='media/profile_image'),
        ),
    ]
